### PR TITLE
Libnotify implemented, Config Window doesn't need Apply/Cancel button anymore

### PR DESCRIPTION
**Pull request by Hubcapp**
Finally got around to this. This needs testing on lots of different Linux platforms (and Windows too just to make sure nothing got messed up, but I doubt it), but as of now "It works on my machine".

To use libnotify, the user must install java-gnome from their repositories. A note about that is displayed if the user doesn't have it installed, but tries to use native notifications anyway. Because this library relies on a package the user has installed on their system, it may be necessary to update our new binary file "gtk-4.1.jar" as the java-gnome project updates. It is also possible that the required version of java-gnome will not be in some distribution's repositories. We will (I will?) have to update the binary gtk-4.1.jar down the road once gtk-4.1 is obsolete in order for the user to be able to install a version of java-gnome that works with rscplus.

I haven't tested if you start the client with non-native notifications on and then change to native. I think the client currently needs to be reset, or else gtk/libnotify won't initialize properly.

### CODE REVIEW

**Comment by Hubcapp** [comment]
I fixed the initilization of gtk/libnotify, and added a bunch of listeners in the ConfigWindow class so that the Cancel and Apply buttons are no longer necessary.

**Comment by OrN** [comment]
Is this ready?

**Comment by Hubcapp** [comment]
I haven't done any testing for it, so it's in the same status as 3 weeks ago.

**Comment by thelegendofbrian** [comment]
I'll test it some today

**Comment by thelegendofbrian** [comment]
@Hubcapp Please add `gtk-4.1.jar` to the `.classpath`

**Comment by thelegendofbrian** [comment]
I started the client with the default config, turned on PM notifications without using libnotify, then I toggled on libnotify and it froze up the client and spat out this message:
```
DANGER: GLib-GObject-WARNING, cannot register existing type 'GdkDisplayManager'
DANGER: GLib-CRITICAL, g_once_init_leave: assertion 'result != 0' failed
DANGER: GLib-GObject-CRITICAL, g_object_new: assertion 'G_TYPE_IS_OBJECT (object_type)' failed```

**Comment by thelegendofbrian** [comment]
Another concern I have is that if a user isn't using the exact version of java-gnome expected, it crashes. I was running on a one version old installation and ran into this:
```
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: 

We anticipated loading the native portion of java-gnome from:
/usr/lib/jni/libgtkjni-4.1.3.so
but didn't find the library there.

	at org.freedesktop.bindings.Plumbing.loadNativeCode(Plumbing.java:205)
	at org.freedesktop.bindings.Plumbing.<clinit>(Plumbing.java:110)
	at org.gnome.gtk.Gtk.init(Gtk.java:95)
	at Client.CheckBoxListener.actionPerformed(ConfigWindow.java:1241)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.JToggleButton$ToggleButtonModel.setPressed(JToggleButton.java:308)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Of course, it was easily solved by updating, but there is a concern that crashes will occur from mismatched versions.

**Comment by thelegendofbrian** [comment]
The view distance slider doesn't seems to go back to the default value after pressing Restore Defaults

**Comment by thelegendofbrian** [comment]
I started the client in a new folder without any config and the view distance slider defaulted to 2,300 instead of the default of 10,000. What happens is when the client loads, it's correctly set to 10,000 in the config, however as soon as the Settings window is opened it saves the incorrect value to the config immediately. Perhaps it's not getting loaded into the slider value properly?

**Comment by thelegendofbrian** [comment]
I got this crash when I opened up the client (and I think I logged in). It could be a completely unrelated error since I only get it once. https://gist.github.com/thelegendofbrian/a509cb8b7f7f0c3aabd84b424a0f70bf

**Comment by Hubcapp** [comment]
I think I should rewrite it to just call the "notify-send" binary instead of actually trying to integrate it into java with java-gnome. would save all this headache with version mismatch

**Comment by Hubcapp** [comment]
>I started the client in a new folder without any config and the view distance slider defaulted to 2,300 instead of the default of 10,000. What happens is when the client loads, it's correctly set to 10,000 in the config, however as soon as the Settings window is opened it saves the incorrect value to the config immediately. Perhaps it's not getting loaded into the slider value properly?

this sounds true

**Comment by OrN** [comment]
What is the status of this pull request?

**Comment by Hubcapp** [comment]
I forgot this was even open. Been busy, not playing rs. I haven't worked on it since I last commented, so it still needs to be rewritten to NOT use java-gnome and load the settings correctly.

I'll get to it at some point...

**Comment by Hubcapp** [comment]
rewriting this today

**Pull request closed without merging**
