### PR TITLE
Updating readme, chatbox scrollbar fix when resizing, and other fixes

### PR DESCRIPTION
**Pull request by lmsv-mx123**

### CODE REVIEW

**Comment by OrN** [comment]
Could you explain what this fixes?

**Comment by lmsv-mx123** [comment]
* The chatbox scrollbar adjusts when resizing
* The your ip address in use limitation is fixed
* The hardcoded inventory of 30 is replaced with the reflected variable
* I added the player region information to debug, as I intend to add toggable rs music later, depending on the player's location

**Comment by OrN** [comment]
Alright looks good

**Comment by thelegendofbrian** [comment]
Very excited to see the music added. Tried hooking player location in the past for this reason, but lacked the knowledge.

**Comment by OrN** [comment]
It will be a nice addition indeed, are you going to use midis?

If somebody wants to do the work and maintain it (changes to the OSRS cache format would break it), we could possibly try to use the OSRS cache to load in it's music, but I don't know if all music is actually present when it downloads the cache, or if it only caches music it needs to play while you play.

**Comment by lmsv-mx123** [comment]
I was thinking of using midis since I do not know how to read off from the OSRS cache and am not aware if they are making a lot of changes to OSRS regions in terms of music, I know that at one point the RS2 music was defined by a multiple of 64x64 (for the case of classic the regions appear to be 48x48 so need to do the map using regions of 48x48).

**Pull request merged**
