### PR TITLE
Check if RSC+ is up to date in client

### PR DESCRIPTION
**Pull request by Hubcapp**
Edit: this is all out of date now. disregard this and look below.

I've guessed at the url the version number file will be at ~~(probably "https://raw.githubusercontent.com/OrN/rscplus/master/src/Client/version.txt")~~ so functionality will have to be checked once merged.

Additionally, I don't think RSC+ had a version number before, so I've taken the liberty of implementing an ISO8601 based version number~~, plus a 2 digit subversion for "Number of updates pushed today (will almost always be "01")~~

~~In order for this to work, anyone who wishes their update to RSC+ to notify users of RSC+ that there is an update will have to do these things:~~

~~1. check current main branch to see if there has already been an update today. (in order to correctly set subversion number)
2. check the current date (ISO8601 is YYYYMMDD)
3. Update Settings.VERSION_NUMBER (or else the client will not be able to tell that it is already up to date, it will believe it is out of date)
4. Update src/client/version.txt (or else the client will think it is up to date when it isn't)~~

~~A script to run on the codebase to automatically do this for you could be created if this is too much work every time you want to push something to master. I wouldn't mind a code-formatting script to get rid of whitespace anyway.~~

### CODE REVIEW

**Comment by Hubcapp** [comment]
Oh yeah, and I added a new chat command "::update" which calls the update script manually (although it will run automatically every time you launch RSC+ and are Welcomed to RuneScape). ::help and README are updated.

**Comment by thelegendofbrian** [comment]
Neat. As far as automating the versioning, we'd ideally want server-side git hooks to do it, which GitHub doesn't support. Alternatively, you could make a script to install client side git hooks to run pre-commit, but keep in mind you'd have to make a .bat and .sh version of it. This is just an idea in case it helps. [About git hooks](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)

**Comment by thelegendofbrian** [comment]
On another note, you might want to add comments with the rules for versioning

**Comment by Hubcapp** [comment]
you know what... if I'm going to have to write 2 git hook scripts to automatically find the line in Settings.java and update it, may as well not take the lazy way out and use a 1 line version.txt file

We'll just have one place where version number is kept...

Closed until I figure out how to keep the version number.

**Comment by Hubcapp** [comment]
got rid of version.txt, could be merged again since this will be the "final" mechanism for checking file version. Would like to make git hook scripts still.

**Comment by Hubcapp** [comment]
Now ant will automatically set the version number for us, but I decided to change the version number format to just have HHmmss as the subversion number. I could have kept using the "number of commits push to master" subversion, but that involves downloading Settings.java, parsing the whole file for current version number, checking that the current date is the same as today, clipping and (possibly) incrementing the subversion depending on whether or not it was last pushed today or not, and then piecing together the version and subversion.

This is completely pointless, so I decided to just change the version number format.

**Comment by Hubcapp** [comment]
This actually isn't the greatest method, because now if the user builds their own jar file, they are on a unique version which will appear "in the future" to versions in the repository. If they build the jar file too often, they will never get any updates from the actual project (although I guess this isn't a problem for most users... they'll just use the precompiled .jar)

And although you'll almost always test your changes before you push them, if you don't do "ant compile" before git push, you'll miss out on updating the version number.

**Comment by Hubcapp** [comment]
Easy solution... I took the stuff to set version out of the compile target, and made a new target "setversion". This target won't be triggered by compiling normally.

We can run "ant setversion" whenever we want to update the version number, and it won't be triggered by automatic jar file creation or by users compiling their own jar file without making any changes.

Additionally, this change would make creating proper git hooks really easy, since the contents of the file should just be one line: "ant setversion"

**Comment by OrN** [comment]
We should be able to use the "ant setversion" in the .travis.yml too (which is weirdly being used for the "Latest" release by deleting it and recreating it)

**Comment by Hubcapp** [comment]
Whatever you think is appropriate... I wasn't sure about it being used in the automatic builds because you'll have an "in the future" version (by between 1 and 10 seconds probably) generated when travis builds the precompiled jar file. It checks the version number in https://raw.githubusercontent.com/OrN/rscplus/master/src/Client/Settings.java, so if the travis build doesn't update that file (by making a commit) then you won't have the same version.

This turns out to not be much of a problem. If you have an "in the future" version (even if it's only by a couple seconds) the version check just considers you "up to date". Still bothers me a little, but in practice it would be OK I think.

**Comment by Hubcapp** [comment]
This is I think ready to merge, so whenever you're convinced it is too, I'd like to get this in quick before everyone updates.

**Comment by OrN** [comment]
LGTM

**Pull request merged**
