### PR TITLE
Renderer: Display days left until RSC is closed

### PR DESCRIPTION
**Pull request by OrN**
This will show how many days are left until RSC closes on the login screen.

Any other suggestions?

### CODE REVIEW

**Comment by lmsv-mx123** [comment]
Maybe have link posted to where they can get a say on alternative to not have rsc shutdown

**Comment by OrN** [comment]
@lmsv-mx123 where do you suggest? And yeah the main reason I stuck it up on there was so people basically knew how long they had to have fun...

**Comment by OrN** [comment]
I'll go ahead and merge, if you want to try to add something open another PR

**Comment by Graxeon** [comment]
Any chance you can make an RSC clone with the RSCplus features? Even if it's offline, single player.

**Comment by OrN** [comment]
RSC+ will always work with any server using the latest client protocol, none exist though that I know of.

**Comment by Graxeon** [comment]
Great to hear! Quite a few people are trying to find an easy to setup server + client that's one click, similar to yours.

EasyRSC is the closest I've been able to find so far, but the setup requires a fair amount of configuration.

**Pull request merged**
