### PR TITLE
Comprehensive item name patch

### PR DESCRIPTION
**Pull request by thelegendofbrian**
- Manually went through every item name and made fixes and improvements
- Depending on the user's preferences, the amount that the names deviate from the original item names can be controlled using the **name_patch_type** config, with the default being **3**:

  0 No item name patching
  1 Purely practical name changes (potion dosages, unidentified herbs, unfinished potions)
  2 Capitalizations and fixed spellings on top of type 1 changes
  3 Reworded vague stuff to be more descriptive on top of type 1 & 2 changes

- Previously, if a user did not want any item name patching, it wasn't possible. Now it is.
- The SQLite database can be used in the future to patch item examine text or to show item info overlays on dropped items only for selected items instead of everything.
- Added documentation for all of the config.ini options
- I ran into a problem with the build file where it copied the MANIFEST.MF from sqlite-jdbc-3.8.11.2.jar and copied it into the rscplus.jar file next to the manifest file. This caused it to read the incorrect manifest and was unable to find the main class. I don't know the purpose of the tmp file you had ANT make, so I simplified it in a way I understood and resolved the problem I was having, so you might pay extra attention to the build.xml in case I took away something you wanted.

### name_patch_type = 1
image

### name_patch_type = 2
image

### name_patch_type = 3
image

### CODE REVIEW

**Comment by OrN** [comment]
I can't check it because I don't have membership, but when you think it's ready to merge just tell me.

**Comment by thelegendofbrian** [comment]
Ah alright, I've tested it quite a bit over the last few days and it seems to work well on all config settings. It should be ready to merge now.

**Comment by OrN** [comment]
This depends on native libraries and although it does provide ARM binaries, I'm getting an unsatisfied link error + for some reason it's breaking the Travis-CI build. May be better to just make some kind of text file config for this just so we don't rely on having binaries built for whatever architecture + OS you're using...

**Comment by thelegendofbrian** [comment]
That's odd, I was able to successfully compile it with ANT on Windows and on a fresh installation of Ubuntu Linux. And it's able to run unpackaged on Eclipse on both OS's. What OS are you using?

**Comment by OrN** [comment]
Arch Linux armv7l

**Comment by OrN** [comment]
[java] Exception in thread "Thread-5" java.lang.UnsatisfiedLinkError: org.sqlite.core.NativeDB._open(Ljava/lang/String;I)V
     [java] 	at org.sqlite.core.NativeDB._open(Native Method)
     [java] 	at org.sqlite.core.DB.open(DB.java:161)
     [java] 	at org.sqlite.core.CoreConnection.open(CoreConnection.java:220)
     [java] 	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
     [java] 	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:24)
     [java] 	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:23)
     [java] 	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
     [java] 	at org.sqlite.JDBC.createConnection(JDBC.java:114)
     [java] 	at org.sqlite.JDBC.connect(JDBC.java:88)
     [java] 	at java.sql.DriverManager.getConnection(DriverManager.java:664)
     [java] 	at java.sql.DriverManager.getConnection(DriverManager.java:270)
     [java] 	at Game.Item.patchItemNames(Unknown Source)
     [java] 	at Game.Item.patchItemNames(Unknown Source)
     [java] 	at m.a(Unknown Source)
     [java] 	at client.f(Unknown Source)
     [java] 	at client.a(Unknown Source)
     [java] 	at e.run(Unknown Source)
     [java] 	at java.lang.Thread.run(Thread.java:745)

Here's the error it gives

**Comment by thelegendofbrian** [comment]
Thanks, I'll keep looking into it

**Comment by OrN** [comment]
Alright, here you go I fixed it. I found an issue report for soft float ARM where somebody built the soft float version, but not the hard float one (which I'm using). So I went ahead and just built the native lib for armhf. :D 

https://dl.dropboxusercontent.com/u/61045381/sqlite-jdbc-3.8.11.2.jar

Replace the sqlite in lib with this one.

**Comment by thelegendofbrian** [comment]
Good find! I see you reverted the revert, is any further action required on my part?

**Comment by OrN** [comment]
Nah, I think it's all good now. I should have just checked this in the first place rofl

**Pull request merged**
