### PR TITLE
Replay fixes

### PR DESCRIPTION
**Pull request by OrN**

### CODE REVIEW

**Comment by sean-niemann** [comment]
What's the point of the replay system? Instead of just using a recorder? (I know it saves a lot of space, but honestly what's the difference besides that..?)

**Comment by OrN** [comment]
Data can be examined, NPC ids, item ids, object ids, etc., and scriptable data gathering

Server tick delays, all kinds of good stuff, and a repeatable test you can use for developing sections of the server/client...

**Comment by sean-niemann** [comment]
I've already done that with my entity grabber script lol, as far as grabbing the data from the server goes

**Comment by sean-niemann** [comment]
Back in 2014

**Comment by sean-niemann** [comment]
It's all in JSON format for everything.

**Comment by OrN** [comment]
Right. You needed that information so you wrote scripts to grab it from the client via a bot API. That API used the client, which based its output on data it received from the server. Here is the problem though... RSC will no longer be online in 64 days.

That server you were grabbing information from will no longer be available, so there is nothing to ever confirm that your server is actually authentic.

> What's the point of the replay system? Instead of just using a recorder? (I know it saves a lot of space, but honestly what's the difference besides that..?)

The fact the replays are a snapshot of the session the user played. I can turn off the frame limit on RSC+, gather a ton of replays, and have it gather data from all KINDS of different perspectives, way quicker than you could ever with your bot script! Maybe even learn something you didn't know before or even notice. Doing all that work alone is hard, but with replays, we can examine tons of the same scenario cases rapidly. Drop rates on monsters killed in replays, entities encountered in replays, item spawns, etc.

Videos do not store all of this information.

**Comment by Hubcapp** [comment]
Hi Sean.

I can appreciate that most of the information that can be gathered with RSC+'s new replay feature has already been gathered well over a decade ago. And I know it can be frustrating to watch people duplicate work that you've already done.

The RSC+ replay feature isn't work that has been done before, because it has never been needed. It's main purpose is to serve as a reference of the all the data exactly as it happened on the real vanilla Jagex RS1 server. As well-intentioned as private server authors are when reproducing the RS1 server code, without something to compare their work to, there is no way to tell how authentic it is, so with the reference being taken offline, it is essential that a replacement reference is created.

Here's a quote that I found interesting from Rodgerwilco: <a href="https://www.reddit.com/r/runescape/comments/8m1cp8/runescape_classic/dzwit1u/?context=1">Private servers will never be able to replicate the game or its formulas, **hell, we even have trouble replicating the 'feel' of the game.**</a>

The RSC+ replay feature is an offline reference that is played in the real client and definitely has the same 'feel' as the original server, because it *is* the original server.

**Comment by sean-niemann** [comment]
You know what?

Well said. And let me emphasize again that you are not only quite talented when it comes to programming (it shows it your code), but also you clearly have a very creative mind. I don't say that to a lot of people. I admire what your doing; keep it up. I'm a moderator on mopar (if you didn't know). I can promote your project on the site so we can get more people aware of what you're trying to accomplish. Honestly dude, I'm impressed with what you've done (I've known about this project since not too long after you started pushing to GitHub). I've been around the scene and back. I've seen it all; but you are bringing something new to the table. Let me know if you are interested in gaining a large audience of your work. I have the power to make your repo blow up (doesn't matter that the community is relatively small, its an interesting concept that you are diligently working on, and people will follow). Respect OrN.

**Pull request merged**
