### PR TITLE
Loader rewrite for applet launching and source cleanup

### PR DESCRIPTION
**Pull request by OrN**
This is some source cleanup as well as the ability to run rscplus in an applet to potentially hack the official runescape client to launch rscplus unofficially.

Obviously if that is successful it is a huge security problem with the official client, but it would be nice to be able to run rscplus in it.

### CODE REVIEW

**Comment by OrN** [comment]
@thelegendofbrian There we go, hopefully I didn't mess anything up

**Comment by OrN** [comment]
Labeling this with help wanted because I currently do not have membership to test any of the changes once you get in-game.

**Comment by thelegendofbrian** [comment]
After I finish my current project, I'll test it some

**Comment by thelegendofbrian** [comment]
Tried running the loader-rewrite branch commit 67d2645. Ran into a crash before the client finished loading. Running Windows 10.

Error:
```
...
[   INFO] Loading resource: /assets/bar.png
[   INFO] Running rsc code, have fun :)
Started applet
Loaded: 1143 frames of animation
Error: ua.VA(8,6,6,0,16740352,512,0) client.HC(-116) client.KC(-92) | ua.a client.y client.a e.run java.lang.Thread.run | java.lang.ArithmeticException: / by zero
error_game_crash
```

Screen it crashes at:
image

**Comment by OrN** [comment]
What happens if you resize the client during the rsc loading screen?

**Comment by thelegendofbrian** [comment]
I tested it about 7 times. I was able to get to the login screen only once without a crash while resizing the width continuously during loading. I also tried just resizing it once, but that failed too. All other tests had the same issue as before.

**Pull request closed without merging**
