### PR TITLE
Fix crashing bug with item sorting

### PR DESCRIPTION
**Pull request by Hubcapp**
Trusted compareToIgnoreCase too much when I wrote this, thought the only values that would come out were 10, 0, and -10. Actually lots of values come out, and sometimes it can crash the game when the location offset erroneously overpowers the alphabetic offset.

Hopefully this patch will stop the crash, but it's pretty rare to trigger it. I was able to get it to trigger somewhat reliably when walking north west from the cow pen after killing lots of cows and having a couple of their drops overlap each other then maximum render distance and maximum zoom out and then when you load the cabbage patch and we get about 50 new cabbage items on the ground, and you keep the cow drops in the same frame, the game crashes.

### CODE REVIEW

**Comment by Hubcapp** [comment]
wow lots of git history garbage, but it can merge automatically at least.

**Comment by thelegendofbrian** [comment]
Not really sure what's up with your fork, but you might consider rebasing it to a more recent commit or just remaking the fork.

**Comment by Hubcapp** [comment]
Yeah, I don't know what went wrong here. Files changed = 1 though. Considered deleting the whole fork and starting over but I don't know that it's necessary...

I think it'll be fixed if this gets merged. @OrN said he had to manually pick my commits last time, I think because of some git garbage. So I guess the commits never actually got added? or something?

**Comment by thelegendofbrian** [comment]
If you look at the graph, I think all your changes are based off of the 014b1a8 commit, so any changes on top of that commit are shown in your history. I think this mostly stems off your git workflow. I'd recommend keeping your fork's master up to date with the upstream master (OrN's master). And then every time you want to make changes, make a new branch based off of the most recent master commit and pull request the changes you commit to that new branch. When your changes have been pulled into the upstream project, you can delete your new branch and just be left with your fork's master.

Git can be a little complicated, but from my understanding, this might fix it: ~~you need to rebase your master to the most recent upstream master commit (e363630) (See https://www.atlassian.com/git/tutorials/rewriting-history/git-rebase) Then you need to make a new branch based off of your fork's master branch and apply the changes to it (make sure to save any changes you've made that aren't on the upstream master first). Then you can pull request using your new branch.~~

Okay, let's just make it easy on ourselves:
1. `git diff` your changes you've made for this pull request and hide it away in a notepad or something for reference
2. Delete your fork and remake it
3. Clone the fork on you local machine
4. Make a new branch with a name related to the pull request you want to submit
5. Edit the branch code to reflect the changes you want
6. Commit the changes and pull request it and you're golden

After OrN pulls your changes in, it's safe to delete that branch because it's already been incorporated into the project, in fact, GitHub will have a notice about that and have a button to delete the branch on your closed pull request, see: 
image

**Comment by Hubcapp** [comment]
Alright, I'll try it.

**Comment by thelegendofbrian** [comment]
And here's the git workflow I'd recommend after this time:

1. You want to make changes to the upstream master
2. Make sure your fork's master is up-to-date with the upstream master (OrN's master) using `git pull upstream master`
3. Then make a new branch based off of your fork's master using `git branch name-of-patch`, then checkout the branch using `git checkout name-of-patch`
4. Make changes to your branch you're now in and commit it when you're done
5. Push the new branch and it's changes to GitHub using `git push origin name-of-patch`
6. Navigate to that branch on GitHub and pull request that branch
7. After the branch has been pulled into the upstream master, you can delete the branch you made or keep it, doesn't matter

A note is if someone makes a change to the upstream master when before you pull request your changes, you'll have to commit your local changes and `git pull upstream name-of-patch` in order to allow your branch to automatically merge with the upstream master.

Hope this helps!

**Pull request closed without merging**
