### PR TITLE
Bug fixes and toggles and colourized text and ::help and SHOW_ITEMINFO grouping/sorting and XP Bar improvements

### PR DESCRIPTION
**Pull request by Hubcapp**
Think these are all the changes I wanted to make. You can read the differences on each of the commits. It'll be possible to have a pretty close to "default" looking interface with the new toggles I added, and Status Display sticks to the top left now. Bug fixes also...

### CODE REVIEW

**Comment by Hubcapp** [comment]
Hope you'll get around to pulling this in soon -- the conflict is just to remove a couple junk lines that git added.

**Comment by OrN** [comment]
Waiting on internet to come in within the next few days

**Comment by Hubcapp** [comment]
Glad to know you're alive. Working on  colorized text in the console output
window now.

**Comment by Hubcapp** [comment]
finished colorized chat text. depends on new lib file https://github.com/fusesource/jansi

**Comment by Hubcapp** [comment]
if (command.equals("bank")) {
	+ return "Hey, everyone, I just tried to do something very silly!";
	+ }
	+ else

It's an easter egg. You can remove it before merging if you don't like it.

**Comment by thelegendofbrian** [comment]
Yeah, I guess it really doesn't matter. You've got some nice changes in this request :)

**Comment by thelegendofbrian** [comment]
A little spoiler: I'm working on an extensive config GUI to toggle all these configs we have since so many now.

**Comment by Hubcapp** [comment]
cool. :P I don't mind .ini editing myself, but I got a request from someone to basically add readme in game (::help).

**Comment by Hubcapp** [comment]
@thelegendofbrian I made some changes to your XP Bar system, hope you agree that they're good changes.

I was thinking of adding a way to permanently keep the XP Bar visible as well; maybe add a toggle button like OSRS client.

**Comment by OrN** [comment]
You should probably fix your git history, I had to cherry pick every single commit you made to merge it.

Master is updated with this branch up to this point now though.

**Comment by Hubcapp** [comment]
I'll close it for now and open a new pull request if I find something else I'd like to improve. Thanks for accepting and merging my changes. :)

**Pull request closed without merging**
